#!/bin/bash
curl https://thefemdomist.com/femdomopoly/assets/icons/ico-collar.svg --output ico-collar.svg
curl https://thefemdomist.com/femdomopoly/assets/icons/ico-mouth.svg --output ico-mouth.svg
curl https://thefemdomist.com/femdomopoly/assets/icons/ico-razor.svg --output ico-razor.svg
curl https://thefemdomist.com/femdomopoly/assets/icons/ico-sph.svg --output ico-sph.svg
curl https://thefemdomist.com/femdomopoly/assets/icons/ico-video.svg --output ico-video.svg
curl https://thefemdomist.com/femdomopoly/assets/icons/ico-dildo.svg --output ico-dildo.svg
curl https://thefemdomist.com/femdomopoly/assets/icons/ico-makeup.svg --output ico-makeup.svg
curl https://thefemdomist.com/femdomopoly/assets/icons/ico-goldenshower.svg --output ico-goldenshower.svg
curl https://thefemdomist.com/femdomopoly/assets/icons/ico-dress.svg --output ico-dress.svg
curl https://thefemdomist.com/femdomopoly/assets/icons/ico-begging.svg --output ico-begging.svg
curl https://thefemdomist.com/femdomopoly/assets/icons/ico-dance.svg --output ico-dance.svg
curl https://thefemdomist.com/femdomopoly/assets/icons/ico-heels.svg --output ico-heels.svg
curl https://thefemdomist.com/femdomopoly/assets/icons/ico-dildo.svg --output ico-dildo.svg
curl https://thefemdomist.com/femdomopoly/assets/icons/ico-foot.svg --output ico-foot.svg
curl https://thefemdomist.com/femdomopoly/assets/icons/ico-maid.svg --output ico-maid.svg
curl https://thefemdomist.com/femdomopoly/assets/icons/ico-vibrator.svg --output ico-vibrator.svg
curl https://thefemdomist.com/femdomopoly/assets/icons/ico-question.svg --output ico-question.svg
curl https://thefemdomist.com/femdomopoly/assets/icons/ico-ass.svg --output ico-ass.svg
curl https://thefemdomist.com/femdomopoly/assets/icons/ico-question.svg --output ico-question.svg
curl https://thefemdomist.com/femdomopoly/assets/icons/ico-mouth.svg --output ico-mouth.svg
curl https://thefemdomist.com/femdomopoly/assets/icons/ico-massage.svg --output ico-massage.svg
curl https://thefemdomist.com/femdomopoly/assets/icons/ico-laundry.svg --output ico-laundry.svg
curl https://thefemdomist.com/femdomopoly/assets/icons/ico-dishes.svg --output ico-dishes.svg
curl https://thefemdomist.com/femdomopoly/assets/icons/ico-vibrator.svg --output ico-vibrator.svg
curl https://thefemdomist.com/femdomopoly/assets/icons/ico-massage.svg --output ico-massage.svg
curl https://thefemdomist.com/femdomopoly/assets/icons/ico-ironing.svg --output ico-ironing.svg
curl https://thefemdomist.com/femdomopoly/assets/icons/ico-car.svg --output ico-car.svg
curl https://thefemdomist.com/femdomopoly/assets/icons/ico-foot.svg --output ico-foot.svg
curl https://thefemdomist.com/femdomopoly/assets/icons/ico-mouth.svg --output ico-mouth.svg
curl https://thefemdomist.com/femdomopoly/assets/icons/ico-blindfold.svg --output ico-blindfold.svg
curl https://thefemdomist.com/femdomopoly/assets/icons/ico-gag.svg --output ico-gag.svg
curl https://thefemdomist.com/femdomopoly/assets/icons/ico-rope.svg --output ico-rope.svg
curl https://thefemdomist.com/femdomopoly/assets/icons/ico-rope.svg --output ico-rope.svg
curl https://thefemdomist.com/femdomopoly/assets/icons/ico-rope.svg --output ico-rope.svg
curl https://thefemdomist.com/femdomopoly/assets/icons/ico-rope.svg --output ico-rope.svg
curl https://thefemdomist.com/femdomopoly/assets/icons/ico-gag.svg --output ico-gag.svg
curl https://thefemdomist.com/femdomopoly/assets/icons/ico-rope.svg --output ico-rope.svg
curl https://thefemdomist.com/femdomopoly/assets/icons/ico-goldenshower.svg --output ico-goldenshower.svg
curl https://thefemdomist.com/femdomopoly/assets/icons/ico-glass.svg --output ico-glass.svg
curl https://thefemdomist.com/femdomopoly/assets/icons/ico-toilet.svg --output ico-toilet.svg
curl https://thefemdomist.com/femdomopoly/assets/icons/ico-toilet.svg --output ico-toilet.svg
curl https://thefemdomist.com/femdomopoly/assets/icons/ico-toilet.svg --output ico-toilet.svg
curl https://thefemdomist.com/femdomopoly/assets/icons/ico-goldenshower.svg --output ico-goldenshower.svg
curl https://thefemdomist.com/femdomopoly/assets/icons/ico-toilet.svg --output ico-toilet.svg
curl https://thefemdomist.com/femdomopoly/assets/icons/ico-toiletroll.svg --output ico-toiletroll.svg
curl https://thefemdomist.com/femdomopoly/assets/icons/ico-toilet.svg --output ico-toilet.svg
curl https://thefemdomist.com/femdomopoly/assets/icons/ico-foot.svg --output ico-foot.svg
curl https://thefemdomist.com/femdomopoly/assets/icons/ico-foot.svg --output ico-foot.svg
curl https://thefemdomist.com/femdomopoly/assets/icons/ico-foot.svg --output ico-foot.svg
curl https://thefemdomist.com/femdomopoly/assets/icons/ico-foot.svg --output ico-foot.svg
curl https://thefemdomist.com/femdomopoly/assets/icons/ico-trample.svg --output ico-trample.svg
curl https://thefemdomist.com/femdomopoly/assets/icons/ico-boot.svg --output ico-boot.svg
curl https://thefemdomist.com/femdomopoly/assets/icons/ico-foot.svg --output ico-foot.svg
curl https://thefemdomist.com/femdomopoly/assets/icons/ico-foot.svg --output ico-foot.svg
curl https://thefemdomist.com/femdomopoly/assets/icons/ico-socks.svg --output ico-socks.svg
curl https://thefemdomist.com/femdomopoly/assets/icons/ico-penis.svg --output ico-penis.svg
curl https://thefemdomist.com/femdomopoly/assets/icons/ico-penis.svg --output ico-penis.svg
curl https://thefemdomist.com/femdomopoly/assets/icons/ico-padlock.svg --output ico-padlock.svg
curl https://thefemdomist.com/femdomopoly/assets/icons/ico-padlock.svg --output ico-padlock.svg
curl https://thefemdomist.com/femdomopoly/assets/icons/ico-penis.svg --output ico-penis.svg
curl https://thefemdomist.com/femdomopoly/assets/icons/ico-penis.svg --output ico-penis.svg
curl https://thefemdomist.com/femdomopoly/assets/icons/ico-penis.svg --output ico-penis.svg
curl https://thefemdomist.com/femdomopoly/assets/icons/ico-penis.svg --output ico-penis.svg
curl https://thefemdomist.com/femdomopoly/assets/icons/ico-bowl.svg --output ico-bowl.svg
curl https://thefemdomist.com/femdomopoly/assets/icons/ico-dog.svg --output ico-dog.svg
curl https://thefemdomist.com/femdomopoly/assets/icons/ico-collar.svg --output ico-collar.svg
curl https://thefemdomist.com/femdomopoly/assets/icons/ico-piggy.svg --output ico-piggy.svg
curl https://thefemdomist.com/femdomopoly/assets/icons/ico-pony.svg --output ico-pony.svg
curl https://thefemdomist.com/femdomopoly/assets/icons/ico-dog.svg --output ico-dog.svg
curl https://thefemdomist.com/femdomopoly/assets/icons/ico-dog.svg --output ico-dog.svg
curl https://thefemdomist.com/femdomopoly/assets/icons/ico-dog.svg --output ico-dog.svg
curl https://thefemdomist.com/femdomopoly/assets/icons/ico-slap.svg --output ico-slap.svg
curl https://thefemdomist.com/femdomopoly/assets/icons/ico-slap.svg --output ico-slap.svg
curl https://thefemdomist.com/femdomopoly/assets/icons/ico-whip.svg --output ico-whip.svg
curl https://thefemdomist.com/femdomopoly/assets/icons/ico-crop.svg --output ico-crop.svg
curl https://thefemdomist.com/femdomopoly/assets/icons/ico-clothespeg.svg --output ico-clothespeg.svg
curl https://thefemdomist.com/femdomopoly/assets/icons/ico-icecubes.svg --output ico-icecubes.svg
curl https://thefemdomist.com/femdomopoly/assets/icons/ico-shower.svg --output ico-shower.svg
curl https://thefemdomist.com/femdomopoly/assets/icons/ico-whip.svg --output ico-whip.svg
curl https://thefemdomist.com/femdomopoly/assets/icons/ico-icecubes.svg --output ico-icecubes.svg
curl https://thefemdomist.com/femdomopoly/assets/icons/ico-cane.svg --output ico-cane.svg
curl https://thefemdomist.com/femdomopoly/assets/icons/ico-ballbusting.svg --output ico-ballbusting.svg
curl https://thefemdomist.com/femdomopoly/assets/icons/ico-boot.svg --output ico-boot.svg
curl https://thefemdomist.com/femdomopoly/assets/icons/ico-penis.svg --output ico-penis.svg
curl https://thefemdomist.com/femdomopoly/assets/icons/ico-ballbusting.svg --output ico-ballbusting.svg
curl https://thefemdomist.com/femdomopoly/assets/icons/ico-hotsauce.svg --output ico-hotsauce.svg
curl https://thefemdomist.com/femdomopoly/assets/icons/ico-whip.svg --output ico-whip.svg
curl https://thefemdomist.com/femdomopoly/assets/icons/ico-whip.svg --output ico-whip.svg
curl https://thefemdomist.com/femdomopoly/assets/icons/ico-dildo.svg --output ico-dildo.svg
curl https://thefemdomist.com/femdomopoly/assets/icons/ico-buttplug.svg --output ico-buttplug.svg
curl https://thefemdomist.com/femdomopoly/assets/icons/ico-vibrator.svg --output ico-vibrator.svg
curl https://thefemdomist.com/femdomopoly/assets/icons/ico-finger.svg --output ico-finger.svg
curl https://thefemdomist.com/femdomopoly/assets/icons/ico-dildo.svg --output ico-dildo.svg
curl https://thefemdomist.com/femdomopoly/assets/icons/ico-dildo.svg --output ico-dildo.svg
curl https://thefemdomist.com/femdomopoly/assets/icons/ico-dildo.svg --output ico-dildo.svg
curl https://thefemdomist.com/femdomopoly/assets/icons/ico-finger.svg --output ico-finger.svg
curl https://thefemdomist.com/femdomopoly/assets/icons/ico-tribute.svg --output ico-tribute.svg
curl https://thefemdomist.com/femdomopoly/assets/icons/ico-tribute.svg --output ico-tribute.svg
curl https://thefemdomist.com/femdomopoly/assets/icons/ico-tribute.svg --output ico-tribute.svg
curl https://thefemdomist.com/femdomopoly/assets/icons/ico-tribute.svg --output ico-tribute.svg
curl https://thefemdomist.com/femdomopoly/assets/icons/ico-tribute.svg --output ico-tribute.svg
curl https://thefemdomist.com/femdomopoly/assets/icons/ico-tribute.svg --output ico-tribute.svg
curl https://thefemdomist.com/femdomopoly/assets/icons/ico-tribute.svg --output ico-tribute.svg
curl https://thefemdomist.com/femdomopoly/assets/icons/ico-tribute.svg --output ico-tribute.svg
curl https://thefemdomist.com/femdomopoly/assets/icons/ico-tribute.svg --output ico-tribute.svg